spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-ticaret
    username: root
    password: 123456
  application:
    name: card-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
